### ISSUE TITLE
[xlsx-extract] a space in the name of the file breaks extraction

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/flatfile-plugins#110]
<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ok6z0)

**Comment by meritmalling** [comment]
@ashleygmulligan2 Should I look for specific context around this one? I've been trying to repo but have been getting successful extractions instead!


![Image](https://github.com/FlatFilers/flatfile-plugins/assets/11151764/41374934-d984-472e-b834-fd6ad32e3193)

**Comment by ashleygmulligan2** [comment]
That's great, I wonder if it was fixed?! It was simply a space in the name of file causing an issue.

**Comment by meritmalling** [comment]
Perfect, then I think it was fixed since I've tried quite a few times and not run into an issue!
