### ISSUE TITLE
Consideration for API Calls Needed Outside of Record and Event in RecordHook Plugin

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/flatfile-plugins#122]
from convo on July 12th with @hansjhoffman.

identified three specific use cases that require API calls outside of the record and event in the RecordHook plugin:

- Getting field information from a sheet
- Performing external API calls
- Retrieving metadata information from a space or workbook

Currently, when these API calls are included within the recordHook plugin, API calls are being executed for every record. These cases would benefit from an extension the recordHook plugin to optimize performance. 

Suggested Solution:
An additional callback could be introduced to the plugin. This callback would serve as a catch-all, allowing users to incorporate the necessary API calls for the identified use cases and ensuring that the API calls would not run on every record.

**Comment by hansjhoffman** [comment]
🤔 Thought about taking inspiration for Jest setup/teardown lifecycle methods, we could introduce another callback as a 3rd param to the `RecordHook` fn that would be called _exactly once_ before the records iteration and the result of that callback would be passed in making it accessible in the normal `recordHook` fn. 

e.g. 

```ts
recordHook(
  "Sheet", 
  (event) => { /* do whatever you need here and return final obj */ }, 
  (record, setup, event) => { /* access result of setup callback in hook */}
);
```

**Comment by hansjhoffman** [comment]
Closed with https://github.com/FlatFilers/flatfile-plugins/pull/162
