### ISSUE TITLE
Ghost rows appear when uploading an XLSX file

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/flatfile-plugins#154]
Let's try to add cell formatting to a few rows with no data and see what the plugin does with those rows. It seems like there's a reason these empty rows are considered records during the export. Perhaps we need to add a check for data in the cell, not just formatting?

**Comment by carlbrugger** [comment]
I can duplicate this by having a row with a cell that contains spaces. I haven't discovered a formatting option on an empty cell that causes empty rows.
