### ISSUE TITLE
Make sure that recordHook properly handles async

### ISSUE THREAD

**Issue by dboskovic** [FlatFilers/flatfile-plugins#206]
the recordHook implementation does not await the child promises right now resulting in an implicit failure mode when individual records return promises.

https://github.com/FlatFilers/flatfile-plugins/blob/main/plugins/record-hook/src/RecordHook.ts#L12

this should likely use a mapAsync function or at least a Promise.all (although we should consider the possibility of too many async requests if not awaiting each. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_15uefg)

**Comment by davidchalifoux** [comment]
Hey, this is currently blocking us from using FlatFile. Any chance that PR could be merged soon? 😄

**Comment by carlbrugger** [comment]
Its top of my list this morning!

**Comment by Arsik36** [comment]
@carlbrugger were you able to look further into this?

**Comment by carlbrugger** [comment]
@Arsik36 @davidchalifoux this fix has been released. Thanks for your patience.
