### ISSUE TITLE
@flatfile/plugin-zip-extractor - Does Not Run When ZIP File Is Uploaded

### ISSUE THREAD

**Issue by colinfrederickson** [FlatFilers/flatfile-plugins#216]
When this code is included in the listener:

`  // Add the Zip extractor to the listener
  // This allows the listener to extract files from ZIP archives
  try {
    listener.use(ZipExtractor());
  } catch (error) {
    console.error('Failed to extract files from ZIP:', error);
  }`
  
  the experience is as follows:
  
  - user uploads a .ZIP file
  - No job is initiated
  - The file is not able to be imported

Loom: https://www.loom.com/share/e9a22ab40acd45caa3e5391d5ff626a4 (included XLSX for comparision)

File: 
[CSV_Files_2023-08-03T17-45-23-467Z.zip](https://github.com/FlatFilers/flatfile-plugins/files/12489344/CSV_Files_2023-08-03T17-45-23-467Z.zip)

**Comment by colinfrederickson** [comment]
Update: this appears to be resolved when using older versions of the packages. Do we have any idea what the minimum packages needed to support the plugin are?

**Comment by carlbrugger** [comment]
All plugins have been updated to use version `^0.3.15` of `@flatfile/listener`.

Guide update: https://github.com/FlatFilers/Guides/pull/749#event-10258798135 (Thanks @colinfrederickson!)

**Comment by carlbrugger** [comment]
Closing with https://github.com/FlatFilers/Guides/pull/752
