### ISSUE TITLE
Trigger recordHook w/o caching for syncronous work

### ISSUE THREAD

**Issue by carlbrugger** [FlatFilers/flatfile-plugins#228]
> this request came up in a WD implementation where they want to be able to trigger the record hook without caching so they can perform the operation synchronously.
> Feels like that might be something we can add an option for?

**Comment by colinfrederickson** [comment]
@carlbrugger - wanted to check in on this one to see if there has been any movement / update?

**Comment by carlbrugger** [comment]
@colinfrederickson no movement on this yet.
