### ISSUE TITLE
Make the record hook engine only send patches for updated records.

### ISSUE THREAD

**Issue by bangarang** [FlatFilers/flatfile-plugins#270]
We need to work on making the record hook engine only send patches for updated records. This should try to not send any data to the server that is a noop. 

I think we may need to save the original value to the cache, then do a diff of the original and the final updated value on `event.afterAll()` here so that we can be sure that the updates are real.

**Comment by ncronquist** [comment]
For the Workbook Settled (Commit Completed) work, there is a change in the update records logic that will automatically complete a commit associated to the records update from the record hook plugin.

If the recordHook plugin is going to handle the logic of not sending noop patches, then it will need to complete the associated commit by making a request to the complete commit endpoint:

```sh
curl --location --request POST "${FLATFILE_BASE_URL}/v1/commits/${COMMIT_ID}/complete" \
--header 'Accept: application/json' \
--header "Authorization: Bearer ${FLATFILE_API_KEY}"
```
