### ISSUE TITLE
recordHook updates - Cache and lifecycle methods + commit versus records

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/flatfile-plugins#37]
https://github.com/FlatFilers/platform-sdk-mono/pull/411

Follow example in this PR to add cache and lifecycle methods.

Additionally, switch from listening for records and instead use commit

Lets also get event passed in as well. Currently, only records is.

**Comment by bangarang** [comment]
This PR partially finished this ticket by adding cache and lifecycle methods: [https://github.com/FlatFilers/flatfile-plugins/pull/45](PR #45)

Still need to use `commit:created` instead of `records:*`

**Comment by ashleygmulligan2** [comment]
Thank you, made a new ticket
