### ISSUE TITLE
Make sure that Files extracted from an extractor plugin get charged properly

### ISSUE THREAD

**Issue by bangarang** [FlatFilers/flatfile-plugins#370]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1713975922487449)

Hey team, we've discovered that when you upload XSLX files using plugin-xlsx-extractor, we are not counting these as file imports from a billing perspective, i.e. there are no file import usage events being generated

[Slack Thread](https://flatfile.slack.com/archives/CTVRSGLF8/p1703633509144119)

**Comment by alnoorp** [comment]
This is a known issue that @dboskovic says is not a big deal.
