### ISSUE TITLE
Gaps in the '@flatfile/plugin-convert-json-schema' plugin

### ISSUE THREAD

**Issue by nwoolls** [FlatFilers/flatfile-plugins#523]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1714680549070319)

We are trying to use the `@flatfile/plugin-convert-json-schema` plugin to accelerate our migration from v3 to DXP and running into several gaps, including:

* No support for labels found in the JSON Schema
* No support for Regular Expression validation found in the JSON Schema
* No support for enumerations found in the JSON Schema

I've put together a example that demonstrates these gaps here:

https://github.com/nwoolls/spl-flatfile-json-schema-conversion-gaps

Can these gaps be addressed?

Side note: it would be nice if there was a one-off way to convert JSON Schema to the Blueprint format so we can adopt the Blueprint format but automate the conversion.

**Comment by Arsik36** [comment]
Hey Nate, I'm sorry for the confusion here! This plugin isn't designed to specifically convert JSON schemas from v3, it's designed for JSON Schema specification 2020-12, so a less specific implementation that wouldn't include regex or the enums we included in our Flatfile schemas.
