### ISSUE TITLE
Plugin Maintenance Strategy

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/flatfile-plugins#58]
We need a scalable way in which plugins can be maintained and kept up to date and things change. For instance, when listener gets updated, all plugins using it should be get updated and produce a new package version.

**Comment by alexhollenbeck** [comment]
So, I initially thought this as well, and used pnpm workspaces to achieve that by having certain core dependencies like listener, api etc live at the workspace level. But after a conversation with @dboskovic we decided against this strategy. I'm curious his thoughts on how to approach this.
