### ISSUE TITLE
JSON extractor fails to extract any files on 0.9.0

### ISSUE THREAD

**Issue by amarbakir** [FlatFilers/flatfile-plugins#695]
<img src="https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png" height="16" width="16" alt="Slack logo" /> [#triage-eng-support thread](https://flatfile.slack.com/archives/C05MXFTD04A/p1730491143058519)

I'm pretty confident JSON extractor release [0.9.0](https://www.npmjs.com/package/@flatfile/plugin-json-extractor/v/0.9.0) broke previous behavior. So if you have a working app using 0.8.2 and update to 0.9.0, the 0.9.0 JSON extractor doesn't work for both a valid, populated JSON array as well as an empty array (both cases are handled elegantly in 0.8.2). Both cases fail with this error:
```
Event Received: file:created
TypeError: Cannot read properties of undefined (reading 'get')
    at Object.callback (/Users/amarbakir/dev/FlatfileApp/.flatfile/develop.js:96647:46)
    at exports.Client.trigger (/Users/amarbakir/dev/FlatfileApp/node_modules/@flatfile/listener/dist/index.cjs:1:6431)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async exports.Client.dispatchEvent (/Users/amarbakir/dev/FlatfileApp/node_modules/@flatfile/listener/dist/index.cjs:1:6214)
    at async Object.message (/Users/amarbakir/dev/FlatfileApp/node_modules/@flatfile/listener-driver-pubsub/dist/index.js:108:17)
```

Given it was a minor version update, I would expect no breaking changes. Let me know if you'd like any further details on this or help debugging/fixing

Surfaced this here and got a response here: https://github.com/FlatFilers/flatfile-plugins/pull/690#issuecomment-2450780728

Deleting `node_modules` did not work (tried multiple times when I first saw the issue). Given that PR was able to be tested locally with the `@flatfile/util-extractor@2.3.0` update introduced there, I think the suggestion to use `@flatfile/util-extractor@2.2.1` is the correct fix. I'll open that change tonight/this weekend if no one else beats me to it :)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9iprdm)

**Comment by Arsik36** [comment]
Hey Amar, our engineers released an update to plugin-json-extractor this morning to update the dependency. Please test again with version `0.9.1` and let me know if you still encounter this behavior!

**Comment by amarbakir** [comment]
Awesome, that did the trick! Thanks

**Comment by Arsik36** [comment]
My pleasure!
