### ISSUE TITLE
Add support for other Excel extensions

### ISSUE THREAD

**Issue by shortcarver** [FlatFilers/flatfile-plugins#99]
It looks like the underlying library (https://www.npmjs.com/package/xlsx) can parse a lot more than xlsx files. Please add support for other extensions, or perhaps add the ability to pass the allowed extensions as a part of the options to the xlsxExtractorPlugin() function.

(I'm personally needing xls added)

**Comment by ashleygmulligan2** [comment]
Pass options into the plugin to allow for additional file types.

**Comment by carlbrugger** [comment]
Closed with https://github.com/FlatFilers/flatfile-plugins/pull/150
